#!/bin/bash

## Files and cmd

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
	eww daemon
	sleep 1
fi

## Open widgets
run_eww() {
	eww open-many \
		bar

}

## Launch or close widgets accordingly
# if [[ ! -f "$FILE" ]]; then
# 	touch "$FILE"
# 	run_eww && bspc config -m LVDS-1 top_padding 49
# else
# 	${EWW} close-all && killall eww
# 	rm "$FILE"
# fi
