#!/usr/bin/env bash

# Kill already running process
_ps=(mako xfce-polkit)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof "${_prs}") ]]; then
		killall -9 "${_prs}"
	fi
done

# Polkit agent
/usr/lib/xfce-polkit/xfce-polkit &
