#!/usr/bin/env bash

# Kill already running process
_ps=(xfce-polkit)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof "${_prs}") ]]; then
		killall -9 "${_prs}"
	fi
done

# Polkit agent
/usr/lib/xfce-polkit/xfce-polkit &

# Set wallpaper
# swaybg --output '*' --mode fill --image ~/.config/hypr/wallpapers/wallpaper4.jpg &

