#!/usr/bin/env bash

status=$(connmanctl state | grep State | awk '{print $3}')
essid=$(connmanctl services | grep "[*]A\w" | awk '{$NF="" ; $1="" ; print}')

if [ "$status" == "idle" ]; then
	icon=""
	text=""
	col="#575268"

else
	icon=""
	text="${essid}"
	col="#e48aff"
fi

if [[ "$1" == "--COL" ]]; then
	echo $col
elif [[ "$1" == "--ESSID" ]]; then
	echo "$text"
elif [[ "$1" == "--ICON" ]]; then
	echo $icon
fi
